version: '3.7'
services:
  mysql-elasticjob:
    image: mysql_5.7.25
    container_name: mysql-elasticjob
    ports:
      - '3306:3306'
    volumes:
      - './mysql:/var/lib/mysql'
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: Java12345!
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --lower_case_table_names=1
    networks:
      - mysql_byfn
networks:
  mysql_byfn:
    name: mysql_byfn
    driver: bridge