version: '3'

# Reconfigures the default docker-compose.yml to replace MySQL by Postgres
# Usage: docker-compose -f ./docker-compose.yml -f ./docker-compose-postgres.yml up
services:

  mysql:
    entrypoint: ["echo", "MySQL service is disabled"]

  postgres:
    image: postgres:10
    command: postgres -c 'max_connections=300'
    container_name: dataflow-postgres
    restart: always
    environment:
      POSTGRES_DB: dataflow
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpw
    expose:
      - 5432
    ports:
      - 5432:5432

  dataflow-server:
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/dataflow
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpw
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver

  skipper-server:
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/dataflow
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpw
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver

